logger:
  file:
    level: INFO
    format: <green>{time:YYYY-MM-DD HH:mm:ss}</green>[<level>{level}</level>]<level>{message}</level>
    rotation: "10 MB"
  errorFile:
    level: ERROR
    format: <green>{time:YYYY-MM-DD HH:mm:ss}</green>[<level>{level}</level>]<level>{message}</level>
    rotation: "10 MB"
  console:
    level: DEBUG
    format: <green>{time:YYYY-MM-DD HH:mm:ss}</green>[<level>{level}</level>]<level>{message}</level>